###Estos son los endpoints de la tabla roles
###
GET http://localhost:3000/roles/

###
POST http://localhost:3000/roles
Content-Type: application/json

{
  "nombre": "Profesor"
}

###
DELETE http://localhost:3000/roles/2

###
PATCH http://localhost:3000/roles/3
Content-Type: application/json

{
  "nombre": "Estudiante"
}