GET localhost:3000/reservations/

###
GET localhost:3000/reservations/getbyDate/2024-10-10

###
GET localhost:3000/reservations/getbyRoomId/6

###
GET localhost:3000/reservations/getbyCubicleId/2

###
GET localhost:3000/reservations/getbyUserId/123456711

###
POST http://localhost:3000/reservations
Content-Type: application/json

{
  "fecha": "2024-11-20",
  "horaInicio": "10:00:00",
  "horaFin": "12:00:00",
  "idSala": 7 ,
  "idUsuario": 2021152632,
  "observaciones": "Me gustaria que mariano no llegue",
  "refrigerio": true,
  "idRecursos": [],
  "estado": true,
  "encuestaCompletada": true
}
###
DELETE http://localhost:3000/reservations/deletebyDate/2024-10-05

###
DELETE http://localhost:3000/reservations/300

###
PATCH http://localhost:3000/reservations/26
Content-Type: application/json

{
  "encuestaCompletada": false
}

###
GET http://localhost:3000/reservations/getbyCubicleIdDate/5?startDate=2024-09-23&endDate=2024-09-29
