GET localhost:3000/users/

###
POST localhost:3000/users/login
Content-Type: application/json

{
  "email": "sigierv439@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "cedulaCarnet": 2021152632,
  "nombre": "mariano",
  "correoEmail": "mariano21803@gmail.com",
  "contrasena": "12345",
  "telefono": "88578033",
  "idRol": 1
}

###
DELETE http://localhost:3000/users/2021067590

###
PATCH http://localhost:3000/users/123456711
Content-Type: application/json

{
  "correoEmail": "Brandon@gmail.com"
}

###
POST localhost:3000/users/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "12345"
}